version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска системы сбора и визуализации метрик Grafana.
  grafana:
    container_name: grafana
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: grafana.env
    image: grafana/grafana-oss:main
    # depends_on:
    #   - prometheus
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.rule: "Host(`monitoring.${DOMAIN}`)"
      traefik.http.routers.grafana.service: "grafana"
      traefik.http.routers.grafana.tls.certresolver: "letsencrypt"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
    volumes:
      - "./grafana/data:/var/lib/grafana"

networks:
  default:
    external: true
    name: $NETWORK
